langchain4j:
  open-ai:
    chat-model:
      api-key: ${DASHSCOPE_API_KEY}
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      model-name: qwen3-max
      log-requests: true
      log-responses: true
    streaming-chat-model:
      api-key: ${DASHSCOPE_API_KEY}
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      model-name: qwen3-max
      log-requests: true
      log-responses: true

logging:
  level:
    dev.langchain4j: debug

spring:
  data:
    redis:
      host: 192.168.100.128
      port: 6379
      password: 123321
      database: 0